### ISSUE TITLE
[Question] - Key retrieved no valid version

### ISSUE THREAD

**Issue by random-robbie** [bao7uo/dp_crypto#7]
Hey,

Brilliant work!

I have a target that is returning the key but saying about no valid version found.

I am best just adding the version in or are there more versions that need to be added to this exploit?

```
Found key: C520C3DB23D23942D129B759241242B9D236E3948A1AE142
Total web requests: 1452
No valid version found
```

**Comment by bao7uo** [comment]
I may have missed some versions due to them not all being listed on Telerik's website - in a worst case scenario it should be theoretically possible to brute force it....... could take a while.......

If you do somehow figure out any additional known working version numbers then please include them in a pull request and I'll merge into the exploit. 

Thanks,
Paul
